name: "My Cache Job"
on: [push]
# fork push

jobs:
  my-cache-job:
    name: Cache Job
    runs-on: ['self-hosted']
    env:
      keyOfCache: test-key-1

    steps:
      - uses: actions/checkout@v2
        with:
          repository: testt/actions
          token: ${{ secrets.MY_ACCESS_TOKEN }}
          ref: add-cache-action
          path: ./.github/actions/

      # - uses: 'google-github-actions/auth@v1'
      #   with:
      #     credentials_json: ${{ secrets.TEST_JSON_KEY }}

      - uses: ./.github/actions/cache/
        with:
          path: |
            ./cache
          key: ${{ env.keyOfCache }}
          # restore-keys: | 
          #   test-
          # #  test-

      - name: ls -la ./.github/actions/
        run: ls -la  ./.github/actions/

      - name: ls -la 
        run: ls -la
        
      - name: cat
        run: |
          cat ./cache/mywork.txt || true

      - name: echo 
        run: |
          [ -d cache ] || mkdir cache 
          [ -f cache/mywork.txt ] || echo ${{ env.keyOfCache }} > ./cache/mywork.txt

      #- run: 'wget -P cache/ https://speed.hetzner.de/100MB.bin'

      - name: ls -la 1
        run: ls -la && ls -lh cache/

      #- run: 'rm cache/100MB.bin'

      - name: ls -la 1
        run: ls -la && ls -lh cache/

      - name: cat1
        run: cat ./cache/mywork.txt
